version: "3.9"
services:
  server:
    build: ./apps/server
    ports:
      - "4000:4000"
    volumes:
      - ./apps/server:/app
    working_dir: /app
    command: pnpm start

  client:
    build: ./apps/client
    ports:
      - "5173:5173"
    volumes:
      - ./apps/client:/app
    working_dir: /app
    command: pnpm dev
